# Generated by Django 5.1.7 on 2025-03-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_otp_created_at_customuser_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_confirmation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
